version: '2.1'

services:
  app-cups:
    build: ./app-cups
    network_mode: host
    privileged: true
    ports:
      - '9631:9631'
    labels:
      io.balena.features.dbus: '1'
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
  component-payment-verifone:
    build: ./component-payment-verifone
    network_mode: host
    restart: always
  app-kiosk:
    build: ./app-kiosk
    restart: always
    network_mode: host
    privileged: true
    devices:
      - /dev/dri
    group_add:
      - video
    ports:
      - '80'
  browser:
    image: bh.cr/balenalabs/browser-amd64 
    privileged: true 
    network_mode: host
    ports:
        - '5011' # management API (optional)
        - '35173' # Chromium debugging port (optional)
  wifi-connect:
    image: balenablocks/wifi-connect:amd64
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN
    labels:
      io.balena.features.dbus: "1"
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"