version: '3'
services:
  server:
    build: .
    image: oaklabs/electron-in-docker:latest
    network_mode: host
    privileged: true 
    devices:
      # remove if you dont need to share your graphics card explicitely
      - /dev/dri:/dev/dri
      - /dev/snd:/dev/snd
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/bus/usb:/dev/bus/usb
    environment:
      - NODE_ENV=development
      - DISPLAY=:0